name: Code Coverage

on:
  pull_request:

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:

    - name: Setup lcov
      uses: hrishikesh-kadam/setup-lcov@v1

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate lcov input
      run: |
        chmod +x ./build.sh
        chmod +x ./coverage.sh
        ./coverage.sh

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: build/filtered_coverage.info
        minimum-coverage: 90
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        #working-directory: build/coverage_report
        update-comment: true
